# Site settings
title: Anubhav Srivastava
description: Computer Engineer
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Anubhav Srivastava
user_description: Frontend Enthusiast. Part time open sourcerer. Loves JavaScript ecosystem.
user_title: Web Developer
email: anubhav.srivastava00@gmail.com
twitter_username: trueanubhav
github_username: anubhavsrivastava
facebook_username: theanubhav
linkedin_username: theanubhav
default_username: theanubhav

# Google-analytics
google-analytics:
    id: ''

exclude: ['package.json', 'src', 'node_modules']
